// Code generated by MockGen. DO NOT EDIT.
// Source: api/service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
	time "time"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// PutFile mocks base method
func (m *MockService) PutFile(ctx context.Context, content io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutFile", ctx, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutFile indicates an expected call of PutFile
func (mr *MockServiceMockRecorder) PutFile(ctx, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutFile", reflect.TypeOf((*MockService)(nil).PutFile), ctx, content)
}

// GetFile mocks base method
func (m *MockService) GetFile(ctx context.Context, cb func(string, time.Time, io.ReadSeeker) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetFile indicates an expected call of GetFile
func (mr *MockServiceMockRecorder) GetFile(ctx, cb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockService)(nil).GetFile), ctx, cb)
}
